######################################################################
#
# File name : tb_kara_34bit_wave.do
# Created on: Sat Sep 05 19:25:35 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
