######################################################################
#
# File name : tb_kara_34bit.udo
# Created on: Sat Sep 05 19:25:35 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
