######################################################################
#
# File name : tb_kara_66bit.udo
# Created on: Sat Sep 05 19:13:56 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
