######################################################################
#
# File name : tb_master_compile.do
# Created on: Sat Sep 19 18:22:39 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/work
C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim

C:\\modeltech64_10.6d\\win64\\vlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.6d\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\modeltech64_10.6d\\win64\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../karatsuba_mult.srcs/sources_1/new" \
"../../../../karatsuba_mult.srcs/sources_1/ip/ram_dual/sim/ram_dual.v" \
"../../../../karatsuba_mult.srcs/sources_1/ip/mult_signed_18bit/mult_signed_18bit_sim_netlist.v" \
"../../../../karatsuba_mult.srcs/sources_1/new/kara_mult_34bit.v" \
"../../../../karatsuba_mult.srcs/sources_1/new/kara_mult_66bit.v" \
"../../../../karatsuba_mult.srcs/sources_1/new/karatsuba_top.v" \
"../../../../karatsuba_mult.srcs/sources_1/new/master_clk.v" \
"../../../../karatsuba_mult.srcs/sources_1/new/simpRAM_256x64_control.v" \
"../../../../karatsuba_mult.srcs/sim_1/new/tb_master.v" \


# compile glbl module
C:\\modeltech64_10.6d\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

