######################################################################
#
# File name : tb_master_wave.do
# Created on: Fri Sep 18 11:51:29 +0800 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
